version: '3.8'

services:
  postiz:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dist
    image: localhost/postiz
    ports:
      - "8089:5000"
    environment:
      - DATABASE_URL=$DATABASE_URL
      - REDIS_URL=$REDIS_URL
      - JWT_SECRET=$JWT_SECRET
      - FRONTEND_URL=$FRONTEND_URL
      - NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
      - BACKEND_INTERNAL_URL=$BACKEND_INTERNAL_URL
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY=$CLOUDFLARE_ACCESS_KEY
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKETNAME=$CLOUDFLARE_BUCKETNAME
      - CLOUDFLARE_BUCKET_URL=$CLOUDFLARE_BUCKET_URL
      - CLOUDFLARE_REGION=$CLOUDFLARE_REGION
      - STORAGE_PROVIDER=$STORAGE_PROVIDER
      - X_API_KEY=$X_API_KEY
      - X_API_SECRET=$X_API_SECRETX_CLIENT
      - X_CLIENT=$X_CLIENT
      - X_SECRET=$X_SECRET
      - LINKEDIN_CLIENT_ID=$LINKEDIN_CLIENT_ID
      - LINKEDIN_CLIENT_SECRET=$LINKEDIN_CLIENT_SECRET
      - REDDIT_CLIENT_ID=$REDDIT_CLIENT_ID
      - REDDIT_CLIENT_SECRET=$REDDIT_CLIENT_SECRET
      - GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
      - BEEHIIVE_API_KEY=$BEEHIIVE_API_KEY
      - BEEHIIVE_PUBLICATION_ID=$BEEHIIVE_PUBLICATION_ID
      - THREADS_APP_ID=$THREADS_APP_ID
      - THREADS_APP_SECRET=$THREADS_APP_SECRET
      - FACEBOOK_APP_ID=$FACEBOOK_APP_ID
      - FACEBOOK_APP_SECRET=$FACEBOOK_APP_SECRET
      - YOUTUBE_CLIENT_ID=$YOUTUBE_CLIENT_ID
      - YOUTUBE_CLIENT_SECRET=$YOUTUBE_CLIENT_SECRET
      - TIKTOK_CLIENT_ID=$TIKTOK_CLIENT_ID
      - TIKTOK_CLIENT_SECRET=$TIKTOK_CLIENT_SECRET
      - PINTEREST_CLIENT_ID=$PINTEREST_CLIENT_ID
      - PINTEREST_CLIENT_SECRET=$PINTEREST_CLIENT_SECRET
      - DRIBBBLE_CLIENT_ID=$DRIBBBLE_CLIENT_ID
      - DRIBBBLE_CLIENT_SECRET=$DRIBBBLE_CLIENT_SECRET
      - DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
      - DISCORD_BOT_TOKEN_ID=$DISCORD_BOT_TOKEN_ID
      - SLACK_ID=$SLACK_ID
      - SLACK_SECRET=$SLACK_SECRET
      - SLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET
      - MASTODON_CLIENT_ID=$MASTODON_CLIENT_ID
      - MASTODON_CLIENT_SECRET=$MASTODON_CLIENT_SECRET
      - ENABLE_OPENAI_SELF=$ENABLE_OPENAI_SELF
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - NEXT_PUBLIC_DISCORD_SUPPORT=$NEXT_PUBLIC_DISCORD_SUPPORT
      - NEXT_PUBLIC_POLOTNO=$NEXT_PUBLIC_POLOTNO
      - FEE_AMOUNT=$FEE_AMOUNT
      - STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY
      - STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
      - STRIPE_SIGNING_KEY=$STRIPE_SIGNING_KEY
      - STRIPE_SIGNING_KEY_CONNECT=$STRIPE_SIGNING_KEY_CONNECT
      - NX_ADD_PLUGINS=$NX_ADD_PLUGINS
      - IS_GENERAL=$IS_GENERAL
      - ENABLE_X_SELF=$ENABLE_X_SELF
      - APP_NAME=$APP_NAME
      - APP_DOMAIN=$APP_DOMAIN
      - NODE_ENV=production
    restart: always

